FROM node:10-alpine

WORKDIR /minitwit

COPY package*.json ./
COPY data minitwit/data
COPY server minitwit/server
COPY static minitwit/static
COPY views minitwit/views

RUN npm install

EXPOSE 5000
EXPOSE 5001

WORKDIR /minitwit/server

CMD ["npm", "start"]