FROM python:3.7-alpine

RUN mkdir /minitwit-api-tests

COPY tests/minitwit_sim_api_tests.py /minitwit-api-tests/
COPY tests/requirements.txt /minitwit-api-tests/

WORKDIR /minitwit-api-tests

RUN pip install -r requirements.txt

# EXPOSE 5000 # TODO: Not needed right?

ENTRYPOINT ["pytest", "-s", "minitwit_tests.py"]
