version: '3.6'

networks:
  default:
    name: minitwit-net

services:

  prometheus:
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile
    container_name: minitwit-prometheus
    image: $DOCKER_USERNAME/minitwit-prometheus
    volumes:
      - prometheus-data:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: minitwit-grafana
    volumes:
      - grafana-data:/grafana
    ports:
      - "3000:3000"  

volumes:
  prometheus-data:
  grafana-data: