{
 "title": "API Dashboard",
 "time": { "from": "now-5d", "to": "now-4d" },
 "panels": [
  {
   "title": "Alive",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum by (job) (up)" }
   ]
  },
  {
   "title": "Avg response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, status) (minitwit_responses_sum / minitwit_responses_count)"
    }
   ]
  },
  {
   "title": "Number of responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, status) (minitwit_responses_count)"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minitwit_numOfRequests[5m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (path) (minitwit_responses_sum / minitwit_responses_count)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Node js memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes" }
   ]
  },
  {
   "title": "CPU time - total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}